### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by lucasmz-dev** [maksimowiczm/find-my-ip#1]
Mobile networks and many people's house connections already have IPv6 available, this app only covers IPv4

**Comment by maksimowiczm** [comment]
Yeah sorry for ignorance I totally forgot about IPv6 😅.

I’ll add a setting to change the address provider in the next release.

If you really want to make it work right now, you can modify this line to use `https://api6.ipify.org` or `https://api64.ipify.org`.
https://github.com/maksimowiczm/find-my-ip/blob/88de9af78f5c898ccc6c1bd149f85895b45eb9b3/app/src/main/java/com/maksimowiczm/findmyip/data/network/CurrentAddressDataSource.kt#L56

**Comment by lucasmz-dev** [comment]
You know what would be nice though some extra work? Tracking of both IPv4 and IPv6 addressing rather than one or the other

**Comment by maksimowiczm** [comment]
That is a great idea, but it needs more detailed design.

Displaying the current address is straightforward. If only IPv4 or IPv6 is available, display the address as it is now. If both IPv4 and IPv6 are available, they should be displayed one below the other.

Regarding the address history, it requires additional design. How should it be displayed? Should it appear in the same list as the IPv4 addresses, or should there be separate histories for both? 

Personally, I think the second option (separate lists) is the better one and suggest using [tabs](https://m3.material.io/components/tabs/overview) to switch between the IPv4 and IPv6 histories.

Additionally, I think this should be optional feature (like address history) since not everyone will use or have an IPv6 address and UI will be bloated with useless components. Maybe the application could check for IPv6 availability on the first launch and disable related features if IPv6 is not detected.
